CREATE TABLE
    lid (
        id INTEGER AUTO_INCREMENT PRIMARY KEY,
        isOpen BOOLEAN,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

CREATE TABLE
    light (
        id INTEGER AUTO_INCREMENT PRIMARY KEY,
        isOn BOOLEAN,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );